### PR TITLE
Sort the Categories and gist in alphabetical order

### PR DESCRIPTION
**Pull request by Aracem**

### CODE REVIEW

**Comment by Aracem** [comment]
@AnderWeb @pedrovgs @JcMinarro @ferdy182 ... Please +1 to merge

**Comment by JcMinarro** [comment]
@Aracem  Where could I do a "+1"  on this PR ¿?

**Comment by Aracem** [comment]
": + 1" = :+1:

**Comment by malmstein** [comment]
:dancer:

**Pull request merged**
